### ISSUE TITLE
Inquiry about used technologies

### ISSUE THREAD

**Issue by mehdibo** [Wiqaytna-app/wiqaytna_ios#1]
Hello,

I noticed that the app uses BlueTrace instead of the Google/Apple tracing API.
Any reasons for this decision?

Thanks

**Comment by alouanemed** [comment]
I got a comment, from presumably dev team behind the project, that there will be a white paper released explaining the reasons behind NOT going with Exposure Notification API.

**Comment by iothmane** [comment]
Will wait for the white paper but as it stands it'll be very hard for iOS users to participate in the contact tracing effort without the usage of the ExposureNotification framework. The upside is that the app is compatible with iOS 10 and up.

**Comment by aboullaite** [comment]
The main reason I guess is that the dev started way before Apple/Gooogle released the Tracing API. Given the limited time they had, Wasn't possible to wait until the API is released and a reference implementation is shared. That is simply my personal Opinion

**Comment by nexepu** [comment]
Hello, i think bluetrace is not as efficient as apple's tracing api, as it is almost impossible to keep the app running, the app will be suspended soon after home screen is locked (sooner or later, depending on RAM available, energy consumption and a number of other factors) (ios limitations)

**Comment by ghost** [comment]
in iOS, while the device is in the foreground it will receive advertising packets send out scan requests, and receive scan response packets. In the background, the iOS device (after a fixed amount of time) it will only receive advertising packets. Thus, there's a chance for the app to log connections with other people at least with known devices.

On the other hand, It seems that they added a frequent silent push to wake up the application which will allow the app to have more spare time.

**Comment by aelarassi** [comment]
Closing this question due to inactivity.
Feel free to reply if you do have further comments.
