### ISSUE TITLE
Enable issues in Android repo and how to contribute

### ISSUE THREAD

**Issue by alouanemed** [Wiqaytna-app/wiqaytna_ios#2]
Great initiative by the Moroccan gov!  🎉

It would be awesome If the team behind this project can answer the questions below in order to contribute to the project.

1. Unlike this repo, posting an issue is not enabled in the Android [repo](https://github.com/Wiqaytna-app/wiqaytna_android). Is it intended?
2. Do the reported issues in the app by the users through other means(email, website...) will be posted here?
3. Are you going to share known issues reported by the team or planned features for the upcoming version?

Cheers,

**Comment by aelarassi** [comment]
Thank you!

1. Done!  ✅ 
2. Check this [SECURITY.md](https://github.com/Wiqaytna-app/wiqaytna_ios/blob/master/SECURITY.md)
3. Normally expected just for issues.
