### ISSUE TITLE
Onboarding / UX : Dots 

### ISSUE THREAD

**Issue by mehdinajeddine** [Wiqaytna-app/wiqaytna_ios#5]
On ne comprend pas forcément que les dots sont les étapes d'enroulement.
Peux-tu être rajouter des numéros ?

![screen1](https://user-images.githubusercontent.com/4182002/83683883-02694e80-a5de-11ea-90a3-9f9ef9368ed7.jpeg)

**Comment by aelarassi** [comment]
Closing this question due to inactivity.
Feel free to reply if you do have further comments.
