### ISSUE TITLE
Onboarding / UX : Renvoyer le code 

### ISSUE THREAD

**Issue by mehdinajeddine** [Wiqaytna-app/wiqaytna_ios#6]
Possibilité de rajouter un timer pour les 2 minutes d'attente ?

![screen2](https://user-images.githubusercontent.com/4182002/83684090-5d02aa80-a5de-11ea-8473-c47a1b19d910.jpeg)

**Comment by aelarassi** [comment]
Closing this question due to inactivity.
Feel free to reply if you do have further comments.

**Comment by aelarassi** [comment]
Closing this question due to inactivity.
Feel free to reply if you do have further comments.
